/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;
import modell.Auto;

/**
 *
 * @author RichterBalázsKriszti
 */
public class AutoGUI extends javax.swing.JFrame {
    Auto [] autok;
    int index;
    Auto auto = new Auto();
    public AutoGUI() {
        initComponents();
        tulajdonsagok();
    }
    
    private void tulajdonsagok(){
        String potKerekszam = String.valueOf(auto.getPotkerek());
        String bevanEInditva = auto.isBeinditva() ? "Be" : "Nincs";
        String uzemAnyagMennyiseg = auto.isUzemanyag() ? "Van" : "Nincs";
        potKerekszamTXT.setText(potKerekszam);
        bevanEInditvaTXT.setText(bevanEInditva);
        uzemanyagMennyisegTXT.setText(uzemAnyagMennyiseg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tankolBtn = new javax.swing.JToggleButton();
        leallitBtn = new javax.swing.JToggleButton();
        beinditBtn = new javax.swing.JToggleButton();
        kerekcsereBtn = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        uzemanyagMennyisegTXT = new javax.swing.JLabel();
        potkerekSzamTXT = new javax.swing.JLabel();
        potKerekszamTXT = new javax.swing.JLabel();
        uzemAnyagTxt = new javax.swing.JLabel();
        bevaneinditvaTxt = new javax.swing.JLabel();
        bevanEInditvaTXT = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        autokCbx = new javax.swing.JComboBox<>();
        garazsbaBtn = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        felvetelBtn = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        potkerekCbx = new javax.swing.JComboBox<>();
        nullazasBtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autó funkciók"));

        tankolBtn.setText("Tankolás");
        tankolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankolBtnActionPerformed(evt);
            }
        });

        leallitBtn.setText("Leállítás");
        leallitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leallitBtnActionPerformed(evt);
            }
        });

        beinditBtn.setText("Beindítás");
        beinditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beinditBtnActionPerformed(evt);
            }
        });

        kerekcsereBtn.setText("Kerékcserélés");
        kerekcsereBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerekcsereBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kerekcsereBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tankolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leallitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beinditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beinditBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leallitBtn)
                .addGap(12, 12, 12)
                .addComponent(tankolBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kerekcsereBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kiválasztott autó tulajdonságai", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        uzemanyagMennyisegTXT.setText("s");

        potkerekSzamTXT.setText("Pótkerékszám:");

        potKerekszamTXT.setText("s");

        uzemAnyagTxt.setText("Van-e üzemanyag?");

        bevaneinditvaTxt.setText("Bevan-e indítva?");

        bevanEInditvaTXT.setText("s");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(potkerekSzamTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(potKerekszamTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bevaneinditvaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bevanEInditvaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(uzemAnyagTxt)
                .addGap(18, 18, 18)
                .addComponent(uzemanyagMennyisegTXT)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potkerekSzamTXT)
                    .addComponent(potKerekszamTXT)
                    .addComponent(uzemAnyagTxt)
                    .addComponent(uzemanyagMennyisegTXT)
                    .addComponent(bevanEInditvaTXT)
                    .addComponent(bevaneinditvaTxt))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Garázs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        autokCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--autók" }));

        garazsbaBtn.setText("Jelenlegi autót garázsba");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(garazsbaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autokCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autokCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(garazsbaBtn)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Új ató"));

        felvetelBtn.setText("Felvétel");
        felvetelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                felvetelBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Pótkerék");

        potkerekCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));

        nullazasBtn.setText("Nullázás");
        nullazasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nullazasBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Beindítva");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Üzemanyag");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(nullazasBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(felvetelBtn)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potkerekCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(potkerekCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addGap(4, 4, 4)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nullazasBtn)
                    .addComponent(felvetelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beinditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beinditBtnActionPerformed
        if(auto.isUzemanyag() == true){
            JOptionPane.showMessageDialog(rootPane, "Sikeresen beindítottad a járművet.");
            auto.setBeinditva(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nem tudtad beindítani a járművet, mert nincsen üzemanyag.");
        }
        tulajdonsagok();
    }//GEN-LAST:event_beinditBtnActionPerformed

    private void leallitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leallitBtnActionPerformed
        auto.setBeinditva(false);
        tulajdonsagok();
    }//GEN-LAST:event_leallitBtnActionPerformed

    private void kerekcsereBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerekcsereBtnActionPerformed
        // pótkerék csere
        if(auto.getPotkerek() > 0) {
            JOptionPane.showMessageDialog(rootPane, "Mivel volt pótkerék, igy a kereket sikeresen kicserélted.");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nem lehetséges a kerékcsere, mivel jelenleg nincsen pótkerék.");
        }
        tulajdonsagok();
    }//GEN-LAST:event_kerekcsereBtnActionPerformed

    private void tankolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankolBtnActionPerformed
        if(auto.isBeinditva()== true){
            JOptionPane.showMessageDialog(rootPane, "Nem tudsz tankolni mert az autó be van indítva");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Sikeres tankolás");
        }
        tulajdonsagok();
    }//GEN-LAST:event_tankolBtnActionPerformed

    private void nullazasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nullazasBtnActionPerformed
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_nullazasBtnActionPerformed

    private void felvetelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_felvetelBtnActionPerformed
        autokCbx.addItem("Létrehozott autó");
        autokCbx.setSelectedIndex(1);
        potKerekszamTXT.setText((String) potkerekCbx.getSelectedItem());
        
    }//GEN-LAST:event_felvetelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> autokCbx;
    private javax.swing.JToggleButton beinditBtn;
    private javax.swing.JLabel bevanEInditvaTXT;
    private javax.swing.JLabel bevaneinditvaTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton felvetelBtn;
    private javax.swing.JToggleButton garazsbaBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JToggleButton kerekcsereBtn;
    private javax.swing.JToggleButton leallitBtn;
    private javax.swing.JButton nullazasBtn;
    private javax.swing.JLabel potKerekszamTXT;
    private javax.swing.JComboBox<String> potkerekCbx;
    private javax.swing.JLabel potkerekSzamTXT;
    private javax.swing.JToggleButton tankolBtn;
    private javax.swing.JLabel uzemAnyagTxt;
    private javax.swing.JLabel uzemanyagMennyisegTXT;
    // End of variables declaration//GEN-END:variables
}
